application:
  auth-api:
    email: ${app.config.email}
    password: ${app.config.password}
quarkus:
  rest-client:
    escuelajs-api:
      url: https://api.escuelajs.co
      scope: jakarta.inject.Singleton
      tls-configuration-name: insecure
  http:
    port: 8082
  tls:
    insecure:
      trust-all: true
      hostname-verification-algorithm: NONE
  datasource:
    username: postgres
    password: ${app.config.password}
    jdbc:
      url: jdbc:postgresql://localhost:5432/db_konsulta_cambio
    hibernate-orm:
      database:
        generation: update
      log:
        sql: true
        format-sql: true
        bind-parameters: true
